const generator = require('@babel/generator');
const t = require('@babel/types');
const fs = require('fs');

const ast = t.program([
  t.VariableDeclaration("const", [
    t.VariableDeclarator(
      t.Identifier("path"),
      t.CallExpression(t.Identifier("require"), [t.StringLiteral("path")])
    )
  ]),
  t.VariableDeclaration("const", [
    t.VariableDeclarator(
      t.Identifier("MiniCssExtractPlugin"),
      t.CallExpression(t.Identifier("require"), [
        t.StringLiteral("mini-css-extract-plugin")
      ])
    )
  ]),
  t.VariableDeclaration("const", [
    t.VariableDeclarator(
      t.Identifier("isProduction"),
      t.BinaryExpression(
        "===",
        t.MemberExpression(
          t.MemberExpression(
            t.Identifier("process"),
            t.Identifier("env"),
            false,
            null
          ),
          t.Identifier("NODE_ENV"),
          false,
          null
        ),
        t.StringLiteral("production")
      )
    )
  ]),
  t.ExpressionStatement(
    t.AssignmentExpression(
      "=",
      t.MemberExpression(
        t.Identifier("module"),
        t.Identifier("exports"),
        false,
        null
      ),
      t.ObjectExpression([
        t.ObjectProperty(
          t.Identifier("mode"),
          t.StringLiteral("production"),
          false,
          false,
          null
        ),
        t.ObjectProperty(
          t.Identifier("entry"),
          t.ObjectExpression([
            t.ObjectProperty(
              t.Identifier("app"),
              t.CallExpression(
                t.MemberExpression(
                  t.Identifier("path"),
                  t.Identifier("resolve"),
                  false,
                  null
                ),
                [t.Identifier("__dirname"), t.StringLiteral("src/index.js")]
              ),
              false,
              false,
              null
            )
          ]),
          false,
          false,
          null
        ),
        t.ObjectProperty(
          t.Identifier("output"),
          t.ObjectExpression([
            t.ObjectProperty(
              t.Identifier("path"),
              t.CallExpression(
                t.MemberExpression(
                  t.Identifier("path"),
                  t.Identifier("resolve"),
                  false,
                  null
                ),
                [t.Identifier("__dirname"), t.StringLiteral("dist")]
              ),
              false,
              false,
              null
            ),
            t.ObjectProperty(
              t.Identifier("publicPath"),
              t.StringLiteral("/"),
              false,
              false,
              null
            )
          ]),
          false,
          false,
          null
        ),
        t.ObjectProperty(
          t.Identifier("module"),
          t.ObjectExpression([
            t.ObjectProperty(
              t.Identifier("rules"),
              t.ArrayExpression([
                t.ObjectExpression([
                  t.ObjectProperty(
                    t.Identifier("test"),
                    t.RegExpLiteral("\\.js$", ""),
                    false,
                    false,
                    null
                  ),
                  t.ObjectProperty(
                    t.Identifier("use"),
                    t.StringLiteral("babel-loader"),
                    false,
                    false,
                    null
                  ),
                  t.ObjectProperty(
                    t.Identifier("exclude"),
                    t.CallExpression(
                      t.MemberExpression(
                        t.Identifier("path"),
                        t.Identifier("resolve"),
                        false,
                        null
                      ),
                      [t.Identifier("__dirname"), t.StringLiteral("node_modules")]
                    ),
                    false,
                    false,
                    null
                  )
                ]),
                t.ObjectExpression([
                  t.ObjectProperty(
                    t.Identifier("test"),
                    t.RegExpLiteral("\\.css$", ""),
                    false,
                    false,
                    null
                  ),
                  t.ObjectProperty(
                    t.Identifier("use"),
                    t.ArrayExpression([
                      t.StringLiteral("style-loader"),
                      t.StringLiteral("css-loader")
                    ]),
                    false,
                    false,
                    null
                  )
                ]),
                t.ObjectExpression([
                  t.ObjectProperty(
                    t.Identifier("test"),
                    t.RegExpLiteral("\\.less$", ""),
                    false,
                    false,
                    null
                  ),
                  t.ObjectProperty(
                    t.Identifier("use"),
                    t.ArrayExpression([
                      t.StringLiteral("style-loader"),
                      t.StringLiteral("css-loader"),
                      t.StringLiteral("less-loader")
                    ]),
                    false,
                    false,
                    null
                  )
                ])
              ]),
              false,
              false,
              null
            )
          ]),
          false,
          false,
          null
        ),
        t.ObjectProperty(
          t.Identifier("resolve"),
          t.ObjectExpression([
            t.ObjectProperty(
              t.Identifier("alias"),
              t.ObjectExpression([
                t.ObjectProperty(
                  t.StringLiteral("@src"),
                  t.CallExpression(
                    t.MemberExpression(
                      t.Identifier("path"),
                      t.Identifier("resolve"),
                      false,
                      null
                    ),
                    [t.Identifier("__dirname"), t.StringLiteral("src")]
                  ),
                  false,
                  false,
                  null
                ),
                t.ObjectProperty(
                  t.StringLiteral("prettier"),
                  t.CallExpression(
                    t.MemberExpression(
                      t.Identifier("path"),
                      t.Identifier("resolve"),
                      false,
                      null
                    ),
                    [
                      t.Identifier("__dirname"),
                      t.StringLiteral("node_modules/prettier/standalone.js")
                    ]
                  ),
                  false,
                  false,
                  null
                )
              ]),
              false,
              false,
              null
            )
          ]),
          false,
          false,
          null
        ),
        t.ObjectProperty(
          t.Identifier("plugins"),
          t.ConditionalExpression(
            t.Identifier("isProduction"),
            t.ArrayExpression([
              t.NewExpression(t.Identifier("MiniCssExtractPlugin"), [])
            ]),
            t.ArrayExpression([])
          ),
          false,
          false,
          null
        )
      ])
    )
  )
], [], 'module');


fs.writeFileSync('test.config.js', generator.default(ast).code);